version: '3.8'

services:
  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=orderDB
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paymentDB
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  product-service:
    build: ./product-service
    ports:
      - "3001:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=productDB
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  user-service:
    build: ./user-service
    ports:
      - "3002:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=userDB
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  api-gateway:
    build: ./api-gateway
    ports:
      - "3004:3000"
